<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.14159265359"/>

  <!-- Joints Control in Gazebo -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

  <!-- Geometrical properties -->
  <xacro:property name="link_side" value="0.02"/>
  <xacro:property name="joint_radius" value="0.018"/>
  <xacro:property name="joint_length" value="0.025"/>
  <xacro:property name="l0_length" value="0.001"/>
  <xacro:property name="l1_length" value="0.10"/>
  <xacro:property name="b2_length" value="0.03"/>
  <xacro:property name="l2_length" value="0.10"/>
  <xacro:property name="b3_length" value="0.02"/>
  <xacro:property name="l3_length" value="0.08"/>
  <xacro:property name="l4_length" value="0.05"/>
  <xacro:property name="l5_length" value="0.06"/>
  <xacro:property name="l6_length" value="0.05"/>

  <!-- Materials -->
  <material name="orange">
    <color rgba="1.00 0.67 0.02 1.00"/>
  </material>

  <material name="gray">
    <color rgba="0.80 0.80 0.80 1.00"/>
  </material>

  <!-- Generates a box visual/collision/inertial -->
  <xacro:macro name="prism_vci" params="side length mass:=1 *origin">

    <xacro:macro name="prism_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <box size="${side} ${side} ${length}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:prism_geometry/>
      <material name="orange"/>
    </visual>

    <collision>
      <xacro:prism_geometry/>
    </collision>

    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${(mass/12)*(side*side+length*length)}"
               iyy="${(mass/12)*(side*side+length*length)}"
               izz="${(mass/6)*(side*side)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>

  </xacro:macro>

  <!-- Generates a cylinder visual/collision -->
  <xacro:macro name="cylinder_vc" params="radius length *origin">

    <xacro:macro name="cylinder_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <cylinder length="${length}" radius="${radius}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:cylinder_geometry/>
      <material name="gray"/>
    </visual>

    <collision>
      <xacro:cylinder_geometry/>
    </collision>

  </xacro:macro>

  <!-- Generates child joint of parent -->
  <xacro:macro name="arm_joint" params="child parent dist:=0 axis rpy">

    <joint name="${parent}_${child}_joint" type="revolute">
      <origin xyz="0 0 ${dist}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${axis}"/>
      <limit effort="40.0"
             velocity="1.0"
             lower="${-PI}"
             upper="${PI}"/>
    </joint>

    <!-- Required for ROS control -->
    <transmission name="${parent}_${child}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${parent}_${child}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${parent}_${child}_actuator"/>
    </transmission>

    <link name="${parent}">

      <xacro:prism_vci length="${dist}" side="${link_side}">
        <origin xyz="0 0 ${dist/2}" rpy="0 0 0"/>
      </xacro:prism_vci>

      <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">

        <xacro:if value="${axis=='0 0 1'}">
          <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
        </xacro:if>

        <xacro:if value="${axis=='1 0 0'}">
          <origin xyz="0 0 ${dist}" rpy="0 ${PI/2} 0"/>
        </xacro:if>

        <xacro:if value="${axis=='0 1 0'}">
          <origin xyz="0 0 ${dist}" rpy="${PI/2} 0 0"/>
        </xacro:if>

      </xacro:cylinder_vc>

    </link>

    <gazebo reference="${parent}">
      <material>Gazebo/Orange</material>
    </gazebo>

  </xacro:macro>

  <!-- World frame (for Gazebo) -->
  <link name="world"/>

  <!-- Arm fixed to world frame  -->
  <joint name="world_l0_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="l0"/>
  </joint>

  <!-- Joints Chain -->
  <xacro:arm_joint parent="l0" child="l1" axis="0 0 1" rpy="0 0 0" dist="${l0_length}"/>
  <!-- <xacro:arm_joint parent="l1" child="b2" axis="1 0 0" rpy="${PI/2} 0 ${PI/2}" dist="${l1_length}"/> -->

  <joint name="l1_b2_joint" type="revolute">
      <origin xyz="0 0 ${l1_length}" rpy="${PI/2} 0 ${PI/2}"/>
      <parent link="l1"/>
      <child link="b2"/>
      <axis xyz="1 0 0"/>
      <limit effort="40.0"
             velocity="1.0"
             lower="${-PI}"
             upper="${PI}"/>
  </joint>

  <link name="l1">
    <xacro:prism_vci length="${l1_length}" side="${link_side}">
      <origin xyz="0 0 ${l1_length/2}" rpy="0 0 0"/>
    </xacro:prism_vci>
    <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
       <origin xyz="0 0 ${l1_length}" rpy="${PI/2} 0 0"/>
    </xacro:cylinder_vc>
  </link>
  
  <joint name="b2_l2_joint" type="fixed">
      <origin xyz="${b2_length} 0 0" rpy="0 0 0"/>
      <parent link="b2"/>
      <child link="l2"/>
      <axis xyz="0 0 1"/>
      <limit effort="40.0"
             velocity="1.0"
             lower="${-PI}"
             upper="${PI}"/>
  </joint>

  <link name="b2">
    <xacro:prism_vci length="${b2_length}" side="${link_side}">
      <origin xyz="${b2_length/2} 0 0" rpy="0 ${PI/2} 0"/>
    </xacro:prism_vci>
    <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
       <origin xyz="${b2_length} 0 0" rpy="0 ${PI/2} 0"/>
    </xacro:cylinder_vc>
  </link>

  <joint name="l2_b3_joint" type="revolute">
      <origin xyz="${b2_length} ${l2_length} 0" rpy="0 0 0"/>
      <parent link="l2"/>
      <child link="b3"/>
      <axis xyz="1 0 0"/>
      <limit effort="40.0"
             velocity="1.0"
             lower="${-PI}"
             upper="${PI}"/>
  </joint>

  <link name="l2">
    <xacro:prism_vci length="${l2_length}" side="${link_side}">
      <origin xyz="0 ${l2_length/2} 0" rpy="${PI/2} 0 0"/>
    </xacro:prism_vci>
    <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
       <origin xyz="0 ${l2_length} 0" rpy="0 ${PI/2} 0"/>
    </xacro:cylinder_vc>
  </link>

  <joint name="b3_l3_joint" type="fixed">
      <origin xyz="-${b3_length*2} 0 0" rpy="-${PI/2} 0 0"/>
      <parent link="b3"/>
      <child link="l3"/>
      <axis xyz="1 0 0"/>
      <limit effort="40.0"
             velocity="1.0"
             lower="${-PI}"
             upper="${PI}"/>
  </joint>

  <link name="b3">
    <xacro:prism_vci length="${b3_length}" side="${link_side}">
      <origin xyz="-${b3_length*1.5} 0 0" rpy="0 ${PI/2} 0"/>
    </xacro:prism_vci>
    <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
       <origin xyz="-${b3_length*2} 0 0" rpy="0 ${PI/2} 0"/>
    </xacro:cylinder_vc>
  </link>

  <xacro:arm_joint parent="l3" child="l4" axis="0 0 1" rpy="0 0 0" dist="${l3_length}"/>
  <xacro:arm_joint parent="l4" child="l5" axis="1 0 0" rpy="0 0 0" dist="${l4_length}"/>
  <xacro:arm_joint parent="l5" child="l6" axis="0 0 1" rpy="0 0 0" dist="${l5_length}"/>

  <!-- End effector -->
  <link name="l6">
    <xacro:prism_vci length="${l6_length}" side="${link_side}">
      <origin xyz="0 0 ${l6_length/2}" rpy="0 0 0"/>
    </xacro:prism_vci>
  </link>

  <gazebo reference="l6">
    <material>Gazebo/Green</material>
  </gazebo>

</robot>