hardware_interface:
  joints:
    - toe_foot_joint
    - foot_leg1_joint
    - leg1_leg2_joint
    - leg2_leg3_joint
    - leg3_leg4_joint
    - leg4_leg5_joint
    - leg5_arm_joint
    - arm_hand_joint
    - hand_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
    - toe_foot_joint
    - foot_leg1_joint
    - leg1_leg2_joint
    - leg2_leg3_joint
    - leg3_leg4_joint
    - leg4_leg5_joint
    - leg5_arm_joint
    - arm_hand_joint
    - hand_finger_joint
