controller_list:
  - name: fake_arm_controller
    joints:
    - l0_l1_joint
    - l1_b2_joint
    - b2_l2_joint
    - l2_b3_joint
    - b3_l3_joint
    - l3_l4_joint
    - l4_l5_joint
    - l5_l6_joint
