# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Control all joints
arm_controller:
  type: "arm_control/JointTrajectoryController"
  joints:
    - l0_l1_joint
    - l1_b2_joint
    - b2_l2_joint
    - l2_b3_joint
    - b3_l3_joint
    - l3_l4_joint
    - l4_l5_joint
    - l5_l6_joint

  gains:
    l0_l1_joint: {p: 100,  d: 10}
    l1_b2_joint: {p: 100,  d: 10}
    b2_l2_joint: {p: 100,  d: 10}
    l2_b3_joint: {p: 100,  d: 10}
    b3_l3_joint: {p: 100,  d: 10}
    l3_l4_joint: {p: 100,  d: 10}
    l4_l5_joint: {p: 100,  d: 10}
    l5_l6_joint: {p: 100,  d: 10}
